### ISSUE TITLE
Could not find module in path: 'dayz/dist/styles.css'

### ISSUE THREAD

**Issue by bonkboykz** [nathanstitt/dayz#45]
Hi!

Can't seem to find compiled styles

```
Could not find module in path: 'dayz/dist/styles.css' relative to '/src/App.js'
```

Reproduction code: https://codesandbox.io/s/optimistic-chatterjee-4pcnk?file=/src/App.js

Is everything alright with the build?

**Comment by nathanstitt** [comment]
Hi @bonkboykz I'm sorry but looks like I had the path to the css slightly incorrect on the README, it should have been: `dayz/dist/dayz.css`. I'll push an update to fix that. The sandbox you linked also had an error due to missing export of the "App" component.  I've forked it and it's working at: https://codesandbox.io/s/morning-http-h3uej

Thanks for reporting the issue!

**Comment by bonkboykz** [comment]
Thank you for response!

That's really odd but I'm getting
<img width="657" alt="image" src="https://user-images.githubusercontent.com/4549476/114511928-31f6d780-9c41-11eb-8680-a166c1a7875f.png">
in the sandbox you've provided

**Comment by nathanstitt** [comment]
Grr. it looks like I didn't actually save the sandbox.  sorry!   I've saved it now and https://codesandbox.io/s/morning-http-h3uej  should be working now 😁
